import os

TOPICS = {
    "artificial_intelligence": {
        "title": "Artificial Intelligence",
        "body": "Artificial intelligence refers to computer systems capable of performing tasks that typically require human cognition, including language understanding, visual perception, and decision-making. The recent wave of progress has been driven largely by large language models trained on vast text corpora, which can generate fluent text, answer questions, and assist with coding by predicting likely continuations of a given input. Beyond language, AI techniques are widely used in image recognition, recommendation systems, and scientific research, where models can identify patterns in data too large or complex for manual analysis. A central challenge in deploying AI systems is ensuring their outputs are reliable and aligned with user intent, since models can produce plausible-sounding but incorrect information, a phenomenon often called hallucination. Organizations adopting AI increasingly pair model outputs with retrieval systems that ground responses in verified source documents, and with human review processes for high-stakes decisions.",
    },
    "quantum_computing": {
        "title": "Quantum Computing",
        "body": "Quantum computing exploits properties of quantum mechanics, such as superposition and entanglement, to perform certain calculations far more efficiently than classical computers. Instead of bits that are strictly zero or one, quantum computers use qubits that can represent combinations of states simultaneously, enabling certain algorithms to explore many possible solutions in parallel. Promising application areas include cryptography, where quantum algorithms could eventually break widely used encryption schemes, and chemistry, where simulating molecular interactions is computationally expensive for classical machines but more natural for quantum systems. Current quantum hardware remains limited by noise and short coherence times, meaning qubits lose their quantum state quickly, which restricts the complexity of problems that can be solved reliably today. Researchers are pursuing error correction techniques and alternative qubit designs, including superconducting circuits and trapped ions, to build larger, more stable quantum processors.",
    },
    "biotechnology": {
        "title": "Biotechnology and Gene Editing",
        "body": "Biotechnology applies biological systems and organisms to develop products and technologies, spanning fields from agriculture to medicine. One of the most significant recent advances is CRISPR-based gene editing, which allows scientists to make precise changes to DNA sequences by guiding an enzyme to cut at a specific location in the genome. This technology has accelerated research into treatments for genetic diseases, since faulty genes can potentially be corrected directly rather than only managing symptoms. Beyond therapeutics, biotechnology techniques are used to engineer crops with improved yield or resistance to pests, and to produce proteins and other compounds using genetically modified microorganisms in industrial fermentation. Ethical and regulatory questions remain prominent in the field, particularly around editing genes in human embryos and the long-term ecological effects of releasing engineered organisms into the environment.",
    },
    "climate_policy": {
        "title": "Climate Policy",
        "body": "Climate policy encompasses the laws, regulations, and international agreements designed to reduce greenhouse gas emissions and adapt to the effects of a changing climate. Carbon pricing mechanisms, including carbon taxes and cap-and-trade systems, aim to make emissions costly so that businesses and consumers have a financial incentive to shift toward cleaner alternatives. International coordination has historically been difficult because the costs of reducing emissions are borne locally while the benefits of a stable climate are shared globally, creating an incentive for individual countries to under-invest in mitigation relative to the collective optimum. Many governments have also introduced subsidies and standards to accelerate the deployment of renewable energy, electric vehicles, and energy-efficient buildings. Adaptation policy, which focuses on managing unavoidable impacts such as sea level rise and more frequent extreme weather, has become an increasingly important complement to mitigation efforts as physical climate impacts have become more apparent.",
    },
    "cybersecurity": {
        "title": "Cybersecurity Fundamentals",
        "body": "Cybersecurity involves protecting computer systems, networks, and data from unauthorized access, disruption, or theft. Common attack vectors include phishing, where attackers trick users into revealing credentials or installing malicious software, and exploitation of unpatched software vulnerabilities that allow attackers to gain unauthorized access to systems. Defense in depth is a foundational principle in the field, meaning organizations layer multiple security controls, such as firewalls, intrusion detection systems, and access controls, so that the failure of any single defense does not lead to a full compromise. Encryption protects data both at rest and in transit, ensuring that intercepted or stolen data remains unreadable without the corresponding decryption key. As organizations have moved workloads to cloud infrastructure, security responsibilities are increasingly shared between the cloud provider, who secures the underlying infrastructure, and the customer, who must correctly configure access controls and monitor their own applications.",
    },
    "space_exploration": {
        "title": "Space Exploration",
        "body": "Space exploration has entered a period of rapid change driven largely by the falling cost of launching payloads into orbit, achieved through reusable rocket technology that recovers and refurbishes boosters rather than discarding them after a single flight. This cost reduction has enabled a much larger number of satellites to be deployed, supporting applications from global internet connectivity to detailed earth observation for agriculture and disaster response. Crewed space missions remain technically demanding due to the need to protect astronauts from radiation, manage life support systems over long durations, and ensure reliable propulsion and re-entry systems. Plans for sustained human presence on the Moon and eventually Mars depend on developing technologies such as in-situ resource utilization, which would allow missions to produce fuel, water, or building materials from local resources rather than transporting everything from Earth. International collaboration and increasingly capable private companies have both played significant roles in shaping the pace and direction of modern space exploration.",
    },
    "semiconductor_industry": {
        "title": "The Semiconductor Industry",
        "body": "The semiconductor industry designs and manufactures the integrated circuits that power virtually all modern electronics, from smartphones to data center servers. Chip manufacturing is extraordinarily capital intensive, requiring facilities called fabs that can cost tens of billions of dollars and rely on a small number of highly specialized equipment suppliers, particularly for the photolithography machines used to print circuit patterns at nanometer scale. This concentration has made semiconductor supply chains a significant geopolitical concern, since a small number of companies and countries control critical stages of production. Demand for advanced chips has been further amplified by the computational requirements of training and running large AI models, which rely on specialized processors optimized for the parallel matrix operations central to neural network computation. Many governments have introduced subsidies and industrial policy aimed at encouraging domestic semiconductor manufacturing capacity to reduce dependence on concentrated foreign supply chains.",
    },
    "electric_vehicles": {
        "title": "Electric Vehicles",
        "body": "Electric vehicles use battery-powered electric motors instead of internal combustion engines, eliminating tailpipe emissions and reducing the number of moving mechanical parts that require maintenance. Battery cost has historically been the largest barrier to adoption, but prices per kilowatt-hour have fallen substantially over the past decade as manufacturing has scaled and chemistry has improved, narrowing the upfront price gap with conventional vehicles. Charging infrastructure remains a key constraint on adoption, particularly for drivers without access to home charging, which has driven investment in public fast-charging networks along highways and in urban areas. Battery range and charging speed continue to improve, though they still generally lag the refueling speed of gasoline vehicles for long-distance travel. The environmental benefit of electric vehicles depends significantly on the carbon intensity of the electricity grid used to charge them, meaning the climate case for EVs strengthens as grids incorporate more renewable generation.",
    },
    "genomics": {
        "title": "Genomics and Personalized Medicine",
        "body": "Genomics is the study of an organism's complete set of DNA, including the genes themselves and the way they interact with each other and the environment. The cost of sequencing a full human genome has fallen dramatically since the first genome was sequenced, from billions of dollars to a few hundred dollars today, making genomic data far more accessible for both research and clinical use. This has enabled the rise of personalized medicine, where treatment decisions can be informed by a patient's specific genetic profile, for example identifying which cancer therapies are most likely to be effective based on the genetic mutations present in a tumor. Large-scale genomic studies have also identified genetic variants associated with risk for many common diseases, though most of these variants individually have a small effect, meaning genetic risk is typically the product of many variants interacting with lifestyle and environmental factors. Privacy and data security are significant concerns in genomics, since genetic data is uniquely identifying and can reveal sensitive information about relatives as well as the individual tested.",
    },
    "blockchain": {
        "title": "Blockchain Technology",
        "body": "A blockchain is a distributed ledger that records transactions across many computers in a way that makes the recorded history difficult to alter retroactively without altering all subsequent blocks and gaining agreement from the network. Each block contains a cryptographic reference to the previous block, forming a chain, and changes to historical records require redoing the computational work for every subsequent block, which becomes prohibitively expensive as the chain grows. Beyond cryptocurrencies, blockchains have been explored for applications such as supply chain tracking, where an immutable record can help verify the provenance of goods, and for smart contracts, which are self-executing agreements encoded directly on the blockchain that automatically perform actions when predefined conditions are met. Scalability and energy consumption have been significant challenges for some blockchain designs, particularly those relying on proof-of-work consensus, which has driven interest in alternative consensus mechanisms such as proof-of-stake that require substantially less computational energy.",
    },
    "renewable_energy_grid": {
        "title": "Integrating Renewable Energy into the Grid",
        "body": "Integrating large amounts of renewable energy, particularly solar and wind, into electricity grids presents technical challenges distinct from those of conventional power plants because renewable output varies with weather conditions rather than being dispatchable on demand. Grid operators address this variability through a combination of forecasting, which predicts renewable output hours or days in advance, and flexible resources such as natural gas plants, battery storage, and demand response programs that can quickly adjust supply or demand to match available generation. Battery storage has become increasingly important as costs have fallen, allowing excess renewable generation during periods of high output to be stored and discharged later when generation is low. Transmission infrastructure also needs to expand and adapt, since the best locations for wind and solar generation are often far from population centers, requiring new long-distance transmission lines to deliver that power where it is needed.",
    },
    "5g_networks": {
        "title": "5G Wireless Networks",
        "body": "5G is the fifth generation of cellular network technology, designed to deliver substantially higher data speeds, lower latency, and greater device density than previous generations. Lower latency is particularly significant for applications that require near-instantaneous responses, such as remote control of industrial equipment or certain augmented reality applications, where delays of even a few hundred milliseconds can be noticeable or disruptive. 5G networks achieve higher capacity partly by using higher frequency radio bands, including millimeter wave spectrum, which can carry more data but travels shorter distances and is more easily blocked by buildings and foliage, requiring a denser network of smaller cell sites compared to earlier cellular generations. Network slicing is a key architectural feature of 5G, allowing operators to partition a single physical network into multiple virtual networks with different performance guarantees, so that, for example, an emergency services application can be guaranteed reliable bandwidth independent of general consumer traffic on the same infrastructure.",
    },
    "robotics_automation": {
        "title": "Robotics and Industrial Automation",
        "body": "Industrial robotics has traditionally focused on repetitive, well-defined tasks in controlled environments such as assembly lines, where robots perform precise, repeatable motions far faster and more consistently than human workers. Advances in machine vision and sensor technology have expanded the range of tasks robots can perform, enabling them to identify and manipulate objects with variable position, orientation, or shape rather than requiring parts to be precisely positioned in advance. Collaborative robots, often called cobots, are designed to work safely alongside human workers in shared spaces, using force-limiting joints and sensors that stop or slow movement if a person comes too close, in contrast to traditional industrial robots that operate in caged, human-free zones. Beyond manufacturing, robotics is increasingly applied in logistics and warehousing, where autonomous mobile robots navigate dynamic environments to transport goods, and in agriculture, where robots can perform tasks such as selective harvesting that require distinguishing ripe from unripe produce.",
    },
    "fintech": {
        "title": "Financial Technology",
        "body": "Financial technology, or fintech, refers to the use of software and digital platforms to deliver financial services that were traditionally provided through banks and other established institutions. Mobile payment platforms have expanded financial access in regions with limited traditional banking infrastructure, allowing transactions to be conducted through basic smartphones without requiring a conventional bank account. Algorithmic lending platforms use alternative data sources and machine learning models to assess creditworthiness, potentially extending credit to borrowers who lack the credit history required by traditional underwriting methods, though this has also raised concerns about transparency and fairness in automated lending decisions. Robo-advisors provide automated investment management services at lower cost than traditional financial advisors by using algorithms to construct and rebalance diversified portfolios based on a client's stated risk tolerance and goals. Regulatory frameworks for fintech continue to evolve, as regulators work to balance encouraging innovation and competition against ensuring consumer protection and financial system stability.",
    },
    "remote_work_trends": {
        "title": "Remote and Hybrid Work Trends",
        "body": "The widespread adoption of remote and hybrid work arrangements has reshaped how organizations think about office space, hiring, and management practices. Companies that have embraced remote work broadly report being able to hire from a much wider geographic talent pool, no longer constrained to candidates within commuting distance of a physical office, though this has also increased competition for skilled workers across regions. Office real estate demand has shifted in many markets as companies reduce their footprint or redesign spaces around collaboration rather than individual desk work, since many employees now perform focused individual tasks from home and use office time primarily for meetings and team interaction. Measuring productivity in remote settings has pushed many organizations toward outcome-based performance evaluation rather than time-based or presence-based metrics, since the latter are poorly suited to a workforce that is not physically observable. Surveys of employee preferences consistently show a strong preference for at least some flexibility in work location among knowledge workers, making remote and hybrid arrangements a significant factor in talent retention and recruitment.",
    },
}


def build_text(topic):
    return f"{topic['title']}\n\n{topic['body']}"


def generate_knowledge_base(output_dir="data/knowledge_base"):
    os.makedirs(output_dir, exist_ok=True)
    count = 0
    for filename, topic in TOPICS.items():
        with open(os.path.join(output_dir, f"{filename}.txt"), "w", encoding="utf-8") as f:
            f.write(build_text(topic))
        count += 1
    return count


if __name__ == "__main__":
    count = generate_knowledge_base()
    print(f"Generated {count} knowledge base documents")
